### ISSUE TITLE
Past Trips?

### ISSUE THREAD

**Issue by NomeQ** [full-path/ridesheet#5]
What is the expectation with the "Trips" tab over time?

Is the intention that the user will create a report, and then delete the old trips from the sheet? Or is there a plan to archive trips that are in the past, via some kind of action or trigger?

**Comment by keviniano** [comment]
The trips tab is intended to be the agency's trip to-do list -- i.e. current-day and future trips. Ideally, each day then can run the "Move past data to review" menu item and move past trips to "Trip Review" where data is validated for reporting. Once post-trip data is entered, then there's another menu item for moving trips to "Trip Archive".

**Comment by NomeQ** [comment]
Oh cool—that makes sense. I think this would be a good workflow to incorporate into a future dashboard if there ever is one.
